name: DesaiDeas
favicon: null
layout_spectrum: 0.7097815843299031
typography_spectrum: 0.8049953482113779
title: 'Musings on the convergence of Business, Technology and Humanity'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8290695718023926
  lightness: 0.5608219045680016
  saturation: 0.12303547072224319
  rhythmicContrast: 0.31310615851543844
purpose: []
