name: DesaiDeas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55543
title: 'Musings on the convergence of Business, Technology and Humanity'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ed1e3a'
    - '#bdbdbd'
    - '#777777'
    - '#2b2b2b'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.31310615851543844
purpose: []
